# Generated by Django 5.1.6 on 2025-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_alter_expense_date_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='Summary',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
