# Generated by Django 5.1.6 on 2025-03-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_remove_expense_summary_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
    ]
